version: '3'
services:
  mongo:
    container_name: ts-gilly-mongo-dev
    build:
      context: .
      dockerfile: docker/mongo.docker
    env_file:
      db.env
    ports:
      - 27017:27017
    networks:
      - db-net

  web:
    container_name: ts-gilly-server-dev
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: docker/server.docker
    env_file:
      db.env
    ports: 
      - 3000:3000 
    networks:
      - db-net
networks:
  db-net:
    driver: bridge